from paquete.Shape import Shape
from paquete.Rectangle import Rectangle
from paquete.Square import Square
from paquete.Triangle import Triangle
from paquete.Isosceles import Isosceles
from paquete.Scalene import Scalene
from paquete.Equilateral import Equilateral
from paquete.TriRectangle import TriRectangle
from paquete.Point import Point
from paquete.Line import Line